const fs = require('fs');

const product = {
    name: 'Celular',
    price: 1000,
    discount: 0.15
}

const parsedObject = JSON.stringify(product);
fs.writeFile(__dirname + '/autoGenerated.json', parsedObject, err => {
    console.log(err || 'Arquivo salvo');
});
